[package]
cjc-version = "1.0.5"
name = "svg_renderer"
version = "0.1.0"
description = "SVG Parser and Renderer in Cangjie"
output-type = "executable"
compile-option = ""
link-option = ""
src-dir = "src"
out-dir = "out"

[dependencies]

[compiler-args]
